[package]
name = "ditto"
version = "0.1.0"
authors = ["Alex Shapiro <alexander.max.shapiro@gmail.com>"]

[dev-dependencies]
regex = "0.1"

[dependencies]
num = "0.1.36"
rand = "0.3"
rustc-serialize = "0.3"
serde = "0.8.13"
serde_json = "0.8.3"
